name: CI/CD Lab

on:
  push:

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Mensaje de bienvenida
        run: echo "¡Bienvenido al laboratorio de CI/CD!"

      - name: Fecha y hora
        run: date

      - name: Versión de Git
        run: git --version